version: "3.3"
services:
  book-lib-db:
    container_name: book-lib-mysql-db
    image: mysql:5.7
    restart: always
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: "book_lib_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-book-lib-db:/var/lib/mysql
volumes:
  vol-book-lib-db:
